// Generated by CoffeeScript 1.12.7
(function() {
  var path;

  path = require('path');

  module.exports = {
    port: 7410,
    dbFilePath: path.join(__dirname, './../database/'),
    secret: 'password key secret'
  };

}).call(this);
