// Generated by CoffeeScript 1.12.7
(function() {
  var apiRouters, app, bodyParser, express, logger, path, taskRouters, userRouters;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  bodyParser = require('body-parser');

  apiRouters = require('./../routes/api');

  userRouters = require('./../routes/user');

  taskRouters = require('./../routes/task');

  app = express();

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use('/api', apiRouters);

  app.use('/api', userRouters);

  app.use('/api', taskRouters);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  app.use(function(err, req, res, next) {
    var ref;
    res.locals.message = err.message;
    res.locals.error = (ref = req.app.get('env') === 'development') != null ? ref : {
      err: {}
    };
    res.status(err.status || 500);
    return res.render('error');
  });

  module.exports = app;

}).call(this);
