// Generated by CoffeeScript 1.12.7
(function() {
  var express, router, userBiz;

  express = require('express');

  router = express.Router();

  userBiz = require('./../bizs/userBiz');

  router.get('/test', function(req, res) {
    return res.send('XXX');
  });

  router.post('/user/register', userBiz.validUserExists, userBiz.register);

  router.post('/user/login', userBiz.login);

  module.exports = router;

}).call(this);
